In [1]:
!pip install dgl

     |████████████████████████████████| 4.4 MB 6.1 MB/s 


In [2]:
import dgl
import torch

DGL backend not selected or invalid.  Assuming PyTorch for now.


Setting the default backend to "pytorch". You can change it in the ~/.dgl/config.json file or export the DGLBACKEND environment variable.  Valid options are: pytorch, mxnet, tensorflow (all lowercase)


Using backend: pytorch


### DGL Graph Construction

In [3]:
source_nodes = torch.LongTensor([0,0,0,0,0])
destination_nodes = torch.LongTensor([1,2,3,4,5])

# Edges: (0,1), (0,2), (0,3), (0,4), (0,5)

g = dgl.graph((source_nodes, destination_nodes), num_nodes=6) # num_nodes is optional

In [6]:
print(g.num_nodes())
print(g.num_edges())
print(g.num_src_nodes())
print(g.num_dst_nodes())
print(g.out_degrees())

6
5
6
6
tensor([5, 0, 0, 0, 0, 0])


### Assigning Node and Edge Features to Graph

Many graph data contain attributes on nodes and edges. Although the types of node and edge attributes can be arbitrary in real world, DGLGraph only accepts attributes stored in tensors (with numerical contents). Consequently, an attribute of all the nodes or edges must have the same shape. In the context of deep learning, those attributes are often called features.

In [7]:
# Assign a 3-dimensional node feature vector for each node.
g.ndata['x'] = torch.rand(6, 3) # shape of feature matrix 'x': (num_nodes, num_features)

# Assign a 4-dimensional edge feature vector for each edge.
g.edata['a'] = torch.rand(5, 4)

# Assign a 5x4 node feature matrix for each node.  Node and edge features in DGL can be multi-dimensional.
g.ndata['y'] = torch.rand(6, 5, 4)

In [9]:
print(g.edata['a'].shape)
print(g.edata['a'])

torch.Size([5, 4])
tensor([[0.1867, 0.9001, 0.1756, 0.4395],
        [0.8044, 0.9233, 0.2546, 0.3940],
        [0.6858, 0.2266, 0.5921, 0.8945],
        [0.3366, 0.8734, 0.0227, 0.6714],
        [0.7393, 0.3779, 0.4420, 0.1522]])


In [11]:
print(g.ndata['x'].shape)
print(g.ndata['x'])

torch.Size([6, 3])
tensor([[0.6537, 0.1834, 0.3923],
        [0.8319, 0.6363, 0.8668],
        [0.6875, 0.9529, 0.6878],
        [0.3345, 0.5809, 0.1746],
        [0.3187, 0.5822, 0.4995],
        [0.8684, 0.3820, 0.8329]])


### Loading and Saving graph

In [12]:
# save graph
dgl.save_graphs('graph.dgl', g)

# load graph
g = dgl.load_graphs('graph.dgl')

In [13]:
print(g)

([Graph(num_nodes=6, num_edges=5,
      ndata_schemes={'y': Scheme(shape=(5, 4), dtype=torch.float32), 'x': Scheme(shape=(3,), dtype=torch.float32)}
      edata_schemes={'a': Scheme(shape=(4,), dtype=torch.float32)})], {})
