<a href="https://colab.research.google.com/github/palash04/Artificial-Intelligence/blob/master/Data_Analysis/NumpyAndPandas_2D_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Two Dimensional Data

# Python : List of lists
# Numpy : 2Darray
# Pandas : DataFrame

In [2]:
import numpy as np
import pandas as pd

In [3]:
# Accessing elements
print (ridership[1,3])
print (ridership[1:3,3:5])
print (ridership[1 , : ])

NameError: ignored

In [4]:
# Vectorized operations on entire array
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[1,1,1],[2,2,2],[3,3,3]])

print (a+b)

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


In [5]:
# Subway ridership for 5 stations on 10 different days
ridership = np.array([
    [   0,    0,    2,    5,    0],
    [1478, 3877, 3674, 2328, 2539],
    [1613, 4088, 3991, 6461, 2691],
    [1560, 3392, 3826, 4787, 2613],
    [1608, 4802, 3932, 4477, 2705],
    [1576, 3933, 3909, 4979, 2685],
    [  95,  229,  255,  496,  201],
    [   2,    0,    1,   27,    0],
    [1438, 3785, 3589, 4174, 2215],
    [1342, 4043, 4009, 4665, 3033]
])

In [6]:
# Find the station with the maximum riders on the first day
max_station = ridership[0, :].argmax() # argmax() returns the index of maximum element

# Find the mean riders per day for that station
mean_for_max = ridership[:,max_station].mean()

# Find the mean ridership overall for comparison
overall_mean = ridership.mean()

print (max_station)
print (mean_for_max)
print (overall_mean)


3
3239.9
2342.6


In [7]:
# Find the mean ridership per day for each subway station
station_riders = ridership.mean(axis=0)
station_riders

array([1071.2, 2814.9, 2718.8, 3239.9, 1868.2])

In [8]:
maximum_daily_ridership = station_riders.max()
minimum_daily_ridership = station_riders.min()

print (maximum_daily_ridership)
print (minimum_daily_ridership)

3239.9
1071.2


In [12]:
# DataFrame Creation

# You can create a dataframe 
df_1 = pd.DataFrame({'A': [0,1,2], 'B': [3,4,5]}, index = [0,1,2])
print (df_1)

# You can also use a list of list or use a 2D Numpy array
df_2 = pd.DataFrame([[1,2,3,4],[5,6,7,8],[9,10,11,12]], index = ['A','B','C'])
print (df_2)

   A  B
0  0  3
1  1  4
2  2  5
   0   1   2   3
A  1   2   3   4
B  5   6   7   8
C  9  10  11  12


In [13]:
# Subway ridership for 5 stations on 10 different days
ridership_df = pd.DataFrame(
    data=[[   0,    0,    2,    5,    0],
          [1478, 3877, 3674, 2328, 2539],
          [1613, 4088, 3991, 6461, 2691],
          [1560, 3392, 3826, 4787, 2613],
          [1608, 4802, 3932, 4477, 2705],
          [1576, 3933, 3909, 4979, 2685],
          [  95,  229,  255,  496,  201],
          [   2,    0,    1,   27,    0],
          [1438, 3785, 3589, 4174, 2215],
          [1342, 4043, 4009, 4665, 3033]],
    index=['05-01-11', '05-02-11', '05-03-11', '05-04-11', '05-05-11',
           '05-06-11', '05-07-11', '05-08-11', '05-09-11', '05-10-11'],
    columns=['R003', 'R004', 'R005', 'R006', 'R007']
)

In [14]:
# Accessing elements
print (ridership_df.iloc[2])

R003    1613
R004    4088
R005    3991
R006    6461
R007    2691
Name: 05-03-11, dtype: int64


In [15]:
print (ridership_df.loc['05-04-11'])

R003    1560
R004    3392
R005    3826
R006    4787
R007    2613
Name: 05-04-11, dtype: int64


In [16]:
print (ridership_df['R003'])

05-01-11       0
05-02-11    1478
05-03-11    1613
05-04-11    1560
05-05-11    1608
05-06-11    1576
05-07-11      95
05-08-11       2
05-09-11    1438
05-10-11    1342
Name: R003, dtype: int64


In [17]:
print (ridership_df.iloc[1,3])

2328


In [18]:
# Accessing multiple columns
print (ridership_df[['R003','R004']])

          R003  R004
05-01-11     0     0
05-02-11  1478  3877
05-03-11  1613  4088
05-04-11  1560  3392
05-05-11  1608  4802
05-06-11  1576  3933
05-07-11    95   229
05-08-11     2     0
05-09-11  1438  3785
05-10-11  1342  4043


In [23]:
# Accessing multiple rows
print (ridership_df.iloc[1:4])

          R003  R004  R005  R006  R007
05-02-11  1478  3877  3674  2328  2539
05-03-11  1613  4088  3991  6461  2691
05-04-11  1560  3392  3826  4787  2613


In [24]:
df = pd.DataFrame({'A':[1,2,3],'B':[4,5,6]})
df

A  B
0  1  4
1  2  5
2  3  6

In [28]:
print (df.sum())
print (df.mean(axis=1))
print (df.values.sum())

A     6
B    15
dtype: int64
0    2.5
1    3.5
2    4.5
dtype: float64
21


In [38]:
riders = ridership_df.iloc[0].argmax()
mean_for_max = ridership_df.iloc[:,riders].mean()
overall_mean = ridership_df.values.mean()

print (overall_mean,mean_for_max)

2342.6 3239.9


In [39]:
# DataFrames are great data structures to represent CSVs !

subway_df = pd.read_csv('/content/drive/My Drive/Artificial Intelligence/DataAnalysis/nyc_subway_weather.csv')

In [40]:
# print first 5 rows
subway_df.head()

UNIT     DATEn     TIMEn  ...  meanwspdi  weather_lat  weather_lon
0  R003  05-01-11  00:00:00  ...       7.86    40.700348   -73.887177
1  R003  05-01-11  04:00:00  ...       7.86    40.700348   -73.887177
2  R003  05-01-11  12:00:00  ...       7.86    40.700348   -73.887177
3  R003  05-01-11  16:00:00  ...       7.86    40.700348   -73.887177
4  R003  05-01-11  20:00:00  ...       7.86    40.700348   -73.887177

[5 rows x 27 columns]

In [42]:
subway_df.describe()

ENTRIESn        EXITSn  ...   weather_lat   weather_lon
count  4.264900e+04  4.264900e+04  ...  42649.000000  42649.000000
mean   2.812486e+07  1.986993e+07  ...     40.728555    -73.938693
std    3.043607e+07  2.028986e+07  ...      0.065420      0.059582
min    0.000000e+00  0.000000e+00  ...     40.600204    -74.014870
25%    1.039762e+07  7.613712e+06  ...     40.688591    -73.985130
50%    1.818389e+07  1.331609e+07  ...     40.720570    -73.949150
75%    3.263049e+07  2.393771e+07  ...     40.755226    -73.912033
max    2.357746e+08  1.493782e+08  ...     40.862064    -73.694176

[8 rows x 21 columns]

In [43]:
def correlation(x,y):
  std_x = (x-x.mean()) / x.std(ddof=0)
  std_y = (y-y.mean()) / y.std(ddof=0)

  return (std_x*std_y).mean()

In [44]:
print (correlation(subway_df['ENTRIESn_hourly'],subway_df['meanprecipi']))

0.03564851577223041


In [45]:
print (correlation(subway_df['ENTRIESn_hourly'],subway_df['ENTRIESn']))

0.5858954707662182


In [46]:
# Vectorized operations on dataframes
df1 = pd.DataFrame({'a':[1,2,3],'b':[4,5,6],'c':[7,8,9]})
df2 = pd.DataFrame({'a':[10,20,30],'b':[40,50,60],'c':[70,80,90]})

print (df1 + df2)

    a   b   c
0  11  44  77
1  22  55  88
2  33  66  99


In [49]:
df1 = pd.DataFrame({'a':[1,2,3],'b':[4,5,6],'c':[7,8,9]})
df2 = pd.DataFrame({'d':[10,20,30],'c':[40,50,60],'b':[70,80,90]})

print (df1 + df2)

    a   b   c   d
0 NaN  74  47 NaN
1 NaN  85  58 NaN
2 NaN  96  69 NaN


In [50]:
grades_df = pd.DataFrame(
    data={'exam1': [43, 81, 78, 75, 89, 70, 91, 65, 98, 87],
          'exam2': [24, 63, 56, 56, 67, 51, 79, 46, 72, 60]},
    index=['Andre', 'Barry', 'Chris', 'Dan', 'Emilio', 
           'Fred', 'Greta', 'Humbert', 'Ivan', 'James']
)

In [52]:
def convert_grade(grade):
  if grade >= 90:
    return 'A'
  elif grade >= 80:
    return 'B'
  elif grade >= 70:
    return 'C' 
  elif grade >= 60:
    return 'D'
  else:
    return 'F'

In [53]:
def convert_grades(grades):
  return grades.applymap(convert_grade)

res_df = convert_grades(grades_df)
print (res_df)

        exam1 exam2
Andre       F     F
Barry       B     D
Chris       C     F
Dan         C     F
Emilio      B     D
Fred        C     F
Greta       A     C
Humbert     D     F
Ivan        A     C
James       B     D


In [54]:
df = pd.DataFrame({
    'a' : [4,5,3,1,2],
    'b' : [20,10,40,50,30],
    'c' : [25,20,5,15,10]
})

In [55]:
def second_largest_in_column(column):
  sorted_column = column.sort_values(ascending=False)
  return sorted_column.iloc[1]

In [56]:
def second_largest(df):
  return df.apply(second_largest_in_column)

In [57]:
second_largest(df)

a     4
b    40
c    20
dtype: int64