<a href="https://colab.research.google.com/github/palash04/Artificial-Intelligence/blob/master/Data_Analysis/NumyAndPandas_1D_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
# reading csv file
# pandas can read large files pretty quickly unlike unicodecsv which takes a lot of time for large data set
daily_engagement = pd.read_csv('/content/drive/My Drive/Artificial Intelligence/DataAnalysis/daily_engagement.csv')

In [ ]:
len(daily_engagement['acct'].unique())

1237

In [ ]:
# numpy (numerical python)
# numpy arrays

In [ ]:
import numpy as np

In [ ]:
# First 20 countries with employment data
countries = np.array(['Afghanistan', 'Albania', 'Algeria', 'Angola', 'Argentina',
    'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas',
    'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium',
    'Belize', 'Benin', 'Bhutan', 'Bolivia',
    'Bosnia and Herzegovina'])

In [ ]:
# Employment data in 2007 for those 20 countries
employement = np.array([55.70000076,  51.40000153,  50.5       ,  75.69999695,
    58.40000153,  40.09999847,  61.5       ,  57.09999847,
    60.90000153,  66.59999847,  60.40000153,  68.09999847,
    66.90000153,  53.40000153,  48.59999847,  56.79999924,
    71.59999847,  58.40000153,  70.40000153,  41.20000076])

In [ ]:
# Accessing elements
print (countries[0])
print (countries[19])

# Slicing elements
print (countries[0:3])
print (countries[:3])
print (countries[17:])
print (countries[:])

# Element types
print (countries.dtype)
print (employement.dtype)
print (np.array([1,2,3,4,5]).dtype)
print (np.array([True,False,False,True]).dtype)
print (np.array(['AL','CA','AZ']).dtype)

Afghanistan
Bosnia and Herzegovina
['Afghanistan' 'Albania' 'Algeria']
['Afghanistan' 'Albania' 'Algeria']
['Bhutan' 'Bolivia' 'Bosnia and Herzegovina']
['Afghanistan' 'Albania' 'Algeria' 'Angola' 'Argentina' 'Armenia'
 'Australia' 'Austria' 'Azerbaijan' 'Bahamas' 'Bahrain' 'Bangladesh'
 'Barbados' 'Belarus' 'Belgium' 'Belize' 'Benin' 'Bhutan' 'Bolivia'
 'Bosnia and Herzegovina']
<U22
float64
int64
bool
<U2


In [ ]:
# looping
for country in countries:
  print ("Examining country {}".format(country))

for i in range(len(countries)):
  country = countries[i]
  country_employement = employement[i]
  print ("Country {} has {} employment".format(country,country_employement))

Examining country Afghanistan
Examining country Albania
Examining country Algeria
Examining country Angola
Examining country Argentina
Examining country Armenia
Examining country Australia
Examining country Austria
Examining country Azerbaijan
Examining country Bahamas
Examining country Bahrain
Examining country Bangladesh
Examining country Barbados
Examining country Belarus
Examining country Belgium
Examining country Belize
Examining country Benin
Examining country Bhutan
Examining country Bolivia
Examining country Bosnia and Herzegovina
Country Afghanistan has 55.70000076 employment
Country Albania has 51.40000153 employment
Country Algeria has 50.5 employment
Country Angola has 75.69999695 employment
Country Argentina has 58.40000153 employment
Country Armenia has 40.09999847 employment
Country Australia has 61.5 employment
Country Austria has 57.09999847 employment
Country Azerbaijan has 60.90000153 employment
Country Bahamas has 66.59999847 employment
Country Bahrain has 60.400001

In [ ]:
print (employement.mean())
print (employement.std())
print (employement.min())
print (employement.max())
print (employement.sum())


58.68500003850001
9.338269113687888
40.09999847
75.69999695
1173.70000077


In [ ]:
# Vectorized operations
a = np.array([1,2,3,4])
b = np.array([1,2,1,2])

print (a + b)
print (a - b)
print (a * b)
print (a / b)
print (a ** b)


[2 4 4 6]
[0 0 2 2]
[1 4 3 8]
[1. 1. 3. 2.]
[ 1  4  3 16]


In [ ]:
# Arithmetic operations between numpy array and a single number
a = np.array([1,2,3,4])
b = 2

print (a + b)
print (a - b)
print (a * b)
print (a ** b)


[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[ 1  4  9 16]


In [ ]:
# Logical operations with Numpy Arrays
a = np.array([True, False, True, False, True])
b = np.array([True, True, True, False,True])

print (a & b)
print (a | b)
print (~b)
print (a | False)

[ True False  True False  True]
[ True  True  True False  True]
[False False False  True False]
[ True False  True False  True]


In [ ]:
# Comparision operations
a = np.array([1,2,3,4,5])
b = 2

print (a > b)
print (a >= b)
print (a < b)
print (a <= b)
print (a == b)
print (a != b)

[False False  True  True  True]
[False  True  True  True  True]
[ True False False False False]
[ True  True False False False]
[False  True False False False]
[ True False  True  True  True]


In [ ]:
a = np.array([1,2,3,4])
b = a
a += np.array([1,1,1,1])  # inplace

print (b)

[2 3 4 5]


In [ ]:
a = np.array([1,2,3,4])
b = a
a = a + np.array([1,1,1,1]) # not in place
print (b)

[1 2 3 4]


In [ ]:
# Pandas series
# A series is similar to numpy array but it has a additional functionality

# Similarities b/w pandas seires ann numpy arrays
# . Accessing elements a[2], a[:4]
# . Looping for x in s
# . Convenient functions s.mean(), s.max()
# . Vectorized operations v1 + v2
# . Implemented in C (fast)


In [ ]:
import pandas as pd

In [ ]:
countries = ['Albania', 'Algeria', 'Andorra', 'Angola', 'Antigua and Barbuda',
             'Argentina', 'Armenia', 'Australia', 'Austria', 'Azerbaijan',
             'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus',
             'Belgium', 'Belize', 'Benin', 'Bhutan', 'Bolivia']

life_expectancy_values = [74.7,  75. ,  83.4,  57.6,  74.6,  75.4,  72.3,  81.5,  80.2,
                          70.3,  72.1,  76.4,  68.1,  75.2,  69.8,  79.4,  70.8,  62.7,
                          67.3,  70.6]

gdp_values = [ 1681.61390973,   2155.48523109,  21495.80508273,    562.98768478,
              13495.1274663 ,   9388.68852258,   1424.19056199,  24765.54890176,
              27036.48733192,   1945.63754911,  21721.61840978,  13373.21993972,
                483.97086804,   9783.98417323,   2253.46411147,  25034.66692293,
               3680.91642923,    366.04496652,   1175.92638695,   1132.21387981]

# Life expectancy and gdp data in 2007 for 20 countries
life_expectancy = pd.Series(life_expectancy_values,index = countries)
gdp = pd.Series(gdp_values,index = countries)


In [ ]:
life_expectancy_mean = life_expectancy.mean()
gdp_mean = gdp.mean()

In [ ]:
# Findings?
# 1. Find the number of countries where both values are above the mean or both are below the mean
# 2. Find the number of countries where one value is above and one value is below

In [ ]:
def variable_correlation(var1,var2):
  both_above = (var1 > var1.mean()) & (var2 > var2.mean())
  both_below = (var1 < var1.mean()) & (var2 < var2.mean())
  is_same_direction = both_above | both_below
  num_same_direction = is_same_direction.sum()
  num_different_direction = len(var1) - num_same_direction

  return (num_same_direction, num_different_direction)


In [ ]:
print (variable_correlation(life_expectancy,gdp))

(17, 3)


In [ ]:
import numpy as np
import pandas as pd

a = np.array([1,2,3,4])
s = pd.Series([1,2,3,4])

s.describe()  # series functionality which numpy array does not have

count    4.000000
mean     2.500000
std      1.290994
min      1.000000
25%      1.750000
50%      2.500000
75%      3.250000
max      4.000000
dtype: float64

In [ ]:
s1 = pd.Series([-10,0,10,20,30])
s2 = pd.Series([8,9,10,11,12])

print ("s1 : ")
print (s1.describe())
print ("s2 : ")
print (s2.describe())



s1 : 
count     5.000000
mean     10.000000
std      15.811388
min     -10.000000
25%       0.000000
50%      10.000000
75%      20.000000
max      30.000000
dtype: float64
s2 : 
count     5.000000
mean     10.000000
std       1.581139
min       8.000000
25%       9.000000
50%      10.000000
75%      11.000000
max      12.000000
dtype: float64


In [ ]:
a = pd.Series([1,2,3,4,5],index=["one","two","three","four","five"])
a

one      1
two      2
three    3
four     4
five     5
dtype: int64

In [ ]:
print (a.loc["two"])  # searches at the given key
print (a[1])
print (a.iloc[1])     # searches at the given index

2
2
2


In [ ]:
countries = [
    'Afghanistan', 'Albania', 'Algeria', 'Angola',
    'Argentina', 'Armenia', 'Australia', 'Austria',
    'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh',
    'Barbados', 'Belarus', 'Belgium', 'Belize',
    'Benin', 'Bhutan', 'Bolivia', 'Bosnia and Herzegovina',
]


employment_values = [
    55.70000076,  51.40000153,  50.5       ,  75.69999695,
    58.40000153,  40.09999847,  61.5       ,  57.09999847,
    60.90000153,  66.59999847,  60.40000153,  68.09999847,
    66.90000153,  53.40000153,  48.59999847,  56.79999924,
    71.59999847,  58.40000153,  70.40000153,  41.20000076,
]

employment = pd.Series(employment_values, index=countries)

def max_employment(employment):
  max_country = employment.idxmax()
  max_value = employment.loc[max_country]
  return (max_country,max_value)

print (max_employment(employment))

('Angola', 75.69999695)


In [ ]:
s1 = pd.Series([1,2,3,4],index=['a','b','c','d'])
s2 = pd.Series([10,20,30,40],index=['c','d','e','f'])

print (s1+s2)

a     NaN
b     NaN
c    13.0
d    24.0
e     NaN
f     NaN
dtype: float64


In [ ]:
sum_result = s1 + s2
print (sum_result.dropna())

c    13.0
d    24.0
dtype: float64
