<a href="https://colab.research.google.com/github/palash04/Artificial-Intelligence/blob/master/Tensorflow_Series/_01_Tensorflow_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![Screenshot 2020-09-17 at 20 12 36](https://user-images.githubusercontent.com/26361028/93486716-239e4280-f922-11ea-98c8-2cebdd5e44c2.png)


In [1]:
import tensorflow as tf

# Initialization of tensors

In [2]:
x = tf.constant(4)
x

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [4]:
x = tf.constant(4, shape=(2,4), dtype=tf.float32)
x

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[4., 4., 4., 4.],
       [4., 4., 4., 4.]], dtype=float32)>

In [5]:
# 2x3 matrix
x = tf.constant([[1,2,3],[4,5,6]])
x

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [7]:
x = tf.ones((3,3))
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [8]:
x = tf.zeros((3,5))
x

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [9]:
x = tf.eye(3) # I for identity matrix
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [10]:
x = tf.random.normal(shape=(3,4,4), mean=0, stddev=1)
print (x)

tf.Tensor(
[[[ 0.5756741  -2.553847    1.0170803  -1.7242271 ]
  [ 0.98861986 -0.95873976  2.1728766   1.6374525 ]
  [-0.9586493   1.3554672   0.48368454  0.1091338 ]
  [ 0.01869251  0.19060339 -0.61049384 -1.5243425 ]]

 [[ 1.6256074   2.4281464   0.49905255 -0.2087348 ]
  [-0.7635567  -1.4348464  -1.037421   -0.8663582 ]
  [-0.49657413  0.13532451  0.24744852 -0.2015142 ]
  [-0.7465528   1.6565493   0.05979561 -0.2069104 ]]

 [[ 0.7943577  -0.7708732  -0.38743564 -0.5797058 ]
  [ 0.45152023  0.7850851   0.8271401  -0.9929536 ]
  [ 0.33273208  0.6001988  -0.6621788  -1.8676323 ]
  [-0.04859941  0.264578    0.8167209   1.8431972 ]]], shape=(3, 4, 4), dtype=float32)


In [12]:
x = tf.random.uniform(shape=(3,3), minval=0, maxval=1)
print (x)

tf.Tensor(
[[0.6904042  0.10619545 0.184852  ]
 [0.51965415 0.66364014 0.5897888 ]
 [0.2489357  0.1086787  0.8501084 ]], shape=(3, 3), dtype=float32)


In [14]:
x = tf.range(10)
x

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [15]:
x = tf.range(start=1, limit=10, delta=2)
x

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 3, 5, 7, 9], dtype=int32)>

In [17]:
# casting 
x = tf.cast(x, dtype=tf.float64)
x

<tf.Tensor: shape=(5,), dtype=float64, numpy=array([1., 3., 5., 7., 9.])>

# Mathematical operations

In [27]:
x = tf.constant([1,2,3])
y = tf.constant([4,5,6])
z = tf.add(x,y)
print (z)

tf.Tensor([5 7 9], shape=(3,), dtype=int32)


In [19]:
z = x + y
z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 7, 9], dtype=int32)>

In [20]:
z = x - y
z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-3, -3, -3], dtype=int32)>

In [21]:
z = tf.divide(x,y)
z

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.25, 0.4 , 0.5 ])>

In [22]:
z = tf.multiply(x,y)
z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 4, 10, 18], dtype=int32)>

In [30]:
z = tf.tensordot(x,y, axes=1)
print (z)

tf.Tensor(32, shape=(), dtype=int32)


In [29]:
z = tf.reduce_sum(x*y, axis=0)
print (z)

tf.Tensor(32, shape=(), dtype=int32)


In [31]:
z = x**5
print (z)

tf.Tensor([  1  32 243], shape=(3,), dtype=int32)


In [32]:
# matrix multiplication
x = tf.random.normal((2,3))
y = tf.random.normal((3,4))
z = tf.matmul(x,y)
print (z)

tf.Tensor(
[[ 0.18068916  0.94358397  0.75250536  0.5566775 ]
 [-2.0500998   2.4427855  -0.84717363 -0.9995479 ]], shape=(2, 4), dtype=float32)


In [34]:
z = x @ y
print (z)

tf.Tensor(
[[ 0.18068916  0.94358397  0.75250536  0.5566775 ]
 [-2.0500998   2.4427855  -0.84717363 -0.9995479 ]], shape=(2, 4), dtype=float32)


# Indexing

In [38]:
x = tf.constant([0, 1, 1, 2, 3, 4, 5, 6, 7])
print (x[:])
print (x[1:])
print (x[1:3])
print (x[::2])
print (x[::-1])

tf.Tensor([0 1 1 2 3 4 5 6 7], shape=(9,), dtype=int32)
tf.Tensor([1 1 2 3 4 5 6 7], shape=(8,), dtype=int32)
tf.Tensor([1 1], shape=(2,), dtype=int32)
tf.Tensor([0 1 3 5 7], shape=(5,), dtype=int32)
tf.Tensor([7 6 5 4 3 2 1 1 0], shape=(9,), dtype=int32)


In [40]:
indices = tf.constant([0,3])
x_ind = tf.gather(x, indices)
print (x_ind)

tf.Tensor([0 2], shape=(2,), dtype=int32)


In [44]:
x = tf.constant([[1,2],
                 [3,4],
                 [5,6]])
print (x[0])
print (x[0, :])
print (x[0, 1:])
print (x[0:2, :])

tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor([2], shape=(1,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


# Reshaping

In [45]:
x = tf.range(9)
print (x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)


In [46]:
x = tf.reshape(x, shape=(3,3))
x

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]], dtype=int32)>

In [47]:
x = tf.transpose(x, perm=[1,0])
x

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]], dtype=int32)>