<a href="https://colab.research.google.com/github/palash04/Artificial-Intelligence/blob/master/LearnPytorch/_Basics_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Initializing tensors

In [2]:
import torch

In [4]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
my_tensor = torch.tensor([[1,2,3],[4,5,6]], dtype = torch.float32,device=device, requires_grad=True)
my_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', requires_grad=True)

In [5]:
print (my_tensor.dtype)

torch.float32


In [6]:
print (my_tensor.device)    # cuda:0 here number 0 specifies the nnumber of gpu on which it is on.

cuda:0


In [7]:
print (my_tensor.shape)

torch.Size([2, 3])


In [8]:
print (my_tensor.requires_grad)

True


In [9]:
# other common initialization methods
x = torch.empty(size=(3,3))
print (x)

tensor([[1.4665e+08, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 6.1657e-44],
        [1.1578e+27, 1.1362e+30, 7.1547e+22]])


In [11]:
x = torch.zeros((3,3))
print (x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [12]:
x = torch.rand((3,3))     # random values between 0 and 1
x

tensor([[0.0818, 0.8393, 0.7035],
        [0.8632, 0.8726, 0.9516],
        [0.3581, 0.9061, 0.1675]])

In [13]:
x = torch.ones((3,3))
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [15]:
x = torch.eye(5,5)    # Identity matrix
x

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [16]:
x = torch.arange(start=0,end=5,step=1)
x

tensor([0, 1, 2, 3, 4])

In [18]:
x = torch.linspace(start=0.1,end=1,steps=10)
x

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])

In [20]:
x = torch.empty(size=(1,5)).normal_(mean=0,std=1)
x

tensor([[-2.4259, -0.4444,  0.0477, -0.5302,  1.9504]])

In [21]:
x = torch.empty(size=(1,5)).uniform_(0,1)
x

tensor([[0.7747, 0.1089, 0.9340, 0.6522, 0.6620]])

In [23]:
# How to initialize and convert tensors to other types (int, float, double)
tensor = torch.arange(4)
print (tensor.bool())

tensor([False,  True,  True,  True])


In [24]:
print (tensor.short())

tensor([0, 1, 2, 3], dtype=torch.int16)


In [26]:
print (tensor.long())
print (tensor.dtype)

tensor([0, 1, 2, 3])
torch.int64


In [27]:
print (tensor.float())  # float 32 bit

tensor([0., 1., 2., 3.])


In [28]:
print (tensor.double())   # float 64 bit

tensor([0., 1., 2., 3.], dtype=torch.float64)


In [29]:
# Array to tensor conversion and vice versa
import numpy as np

In [32]:
np_array = np.zeros((5,5))
tensor = torch.from_numpy(np_array)
print (tensor)
np_array_back = tensor.numpy()
print (np_array_back)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


# Tensor Math and Comparison operations

In [33]:
import torch

In [34]:
x = torch.tensor([1,2,3])
y = torch.tensor([8,9,7])

In [36]:
# Addition
z = x + y
print (z)
z = torch.add(x,y)
print (z)

tensor([ 9, 11, 10])
tensor([ 9, 11, 10])


In [37]:
# Subtraction
z = x-y
z

tensor([-7, -7, -4])

In [40]:
# Division
z = torch.true_divide(x,y)
z

tensor([0.1250, 0.2222, 0.4286])

In [43]:
t = torch.zeros(3)
print (t)
t.add_(x)   # underscore means inplace operation
print (t)

# we can also do inplace like
t += x
print (t)

tensor([0., 0., 0.])
tensor([1., 2., 3.])
tensor([2., 4., 6.])


In [46]:
# Exponentiation
z = x.pow(2)
print (z)
z = x**2
print (z)

tensor([1, 4, 9])
tensor([1, 4, 9])


In [47]:
# Simple comaparison
z = x > 0
print (z)

tensor([True, True, True])


In [49]:
# Matrix Multiplication
x1 = torch.rand((2,5))
x2 = torch.rand((5,3))
x3 = torch.mm(x1,x2)
print (x3)

# or
x3 = x1.mm(x2)
print (x3)

tensor([[0.6462, 1.9212, 1.5114],
        [0.6121, 1.7331, 1.3171]])
tensor([[0.6462, 1.9212, 1.5114],
        [0.6121, 1.7331, 1.3171]])


In [54]:
x1 = torch.rand((2,5))
x2 = torch.rand((3,5)).T
x3 = torch.matmul(x1,x2)
print (x3)

tensor([[1.2136, 1.9217, 0.8818],
        [1.4290, 1.9110, 0.9631]])


In [61]:
# matrix exponentiation
a = torch.rand(4,4)
a.matrix_power(3)

tensor([[2.7508, 3.1160, 2.6357, 1.9635],
        [1.4245, 1.5470, 1.3877, 0.9213],
        [1.3660, 1.4849, 1.3031, 0.8490],
        [2.6476, 3.0434, 2.7014, 1.8014]])

In [63]:
# element wise multiplication
x = torch.tensor([1,2,3])
y = torch.tensor([8,9,7])
z = x*y
z


tensor([ 8, 18, 21])

In [64]:
# dot product
z = x.dot(y)
z

tensor(47)

In [66]:
# Batch Matrix Multiplication
batch = 32
n = 10
m = 20
p = 30

tensor1 = torch.rand((batch, n, m))
tensor2 = torch.rand((batch, m, p))
out_bmm = torch.bmm(tensor1, tensor2)
print (out_bmm)
print (out_bmm.shape)

tensor([[[6.7771, 6.6659, 7.7327,  ..., 5.5169, 6.6287, 5.8030],
         [5.4867, 4.9324, 5.1906,  ..., 3.8128, 6.2363, 4.8783],
         [4.1918, 4.2550, 4.3131,  ..., 3.4286, 4.7369, 4.2867],
         ...,
         [4.7190, 4.3780, 5.4807,  ..., 3.1594, 4.7570, 3.7874],
         [4.1286, 5.2099, 5.1296,  ..., 3.0807, 4.2464, 4.0945],
         [5.7726, 5.2487, 5.7074,  ..., 4.2499, 5.6019, 4.5825]],

        [[4.3670, 4.6592, 5.1273,  ..., 6.5949, 6.3776, 5.4313],
         [3.9371, 4.8978, 4.7979,  ..., 5.2433, 6.3286, 4.7848],
         [3.0182, 3.4730, 3.9389,  ..., 3.4969, 5.2496, 3.4461],
         ...,
         [4.7051, 3.9607, 5.5512,  ..., 5.9657, 6.3053, 4.7585],
         [2.8408, 2.5114, 3.8891,  ..., 3.1482, 4.6872, 3.4666],
         [3.8256, 4.3326, 4.2087,  ..., 4.6142, 5.3847, 3.9803]],

        [[3.5542, 4.4059, 5.0919,  ..., 4.4414, 4.7954, 5.0210],
         [5.2662, 6.7550, 7.1404,  ..., 5.8663, 7.1030, 6.5304],
         [4.3057, 5.1717, 4.4046,  ..., 5.4248, 5.0007, 4.

In [69]:
out_bmm[0].shape

torch.Size([10, 30])

In [4]:
# Example of Broadcasting
x1 = torch.rand((5,5))
x2 = torch.rand((1,5))

z = x1 - x2
z

tensor([[ 0.1349, -0.1426,  0.7106, -0.1891,  0.2367],
        [ 0.5250, -0.4598,  0.0976, -0.4294,  0.2845],
        [ 0.1068, -0.0548,  0.2723, -0.3578, -0.0627],
        [ 0.9109,  0.2586,  0.7162,  0.3891, -0.4681],
        [ 0.4032,  0.2288,  0.1244,  0.4323, -0.4908]])

In [17]:
# other useful tensor operations
x = torch.tensor([[1,2,3],[4,5,6]])
print (x)
print (x.shape)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])


In [18]:
sum_x = torch.sum(x,dim=1)
sum_x

tensor([ 6, 15])

In [19]:
values, indices = torch.max(x,dim=0)
print (values, indices)

tensor([4, 5, 6]) tensor([1, 1, 1])


In [20]:
z = torch.argmax(x,dim=0)   # returns index of max ele
z

tensor([1, 1, 1])

In [21]:
z = torch.mean(x.float(), dim=0)
z

tensor([2.5000, 3.5000, 4.5000])

In [23]:
x = torch.tensor([8,2,3])
y = torch.tensor([8,9,10])
z = torch.eq(x,y)
z

tensor([ True, False, False])

In [26]:
x = torch.tensor([1,4,5,-12,40,12,6,7,-10])
z = torch.clamp(x, min=0)   # relu function
z

tensor([ 1,  4,  5,  0, 40, 12,  6,  7,  0])

In [27]:
x = torch.tensor([1,1,0,0,0,1,1], dtype=torch.bool)
z = torch.any(x)
print (z)
z = torch.all(x)
print (z)

tensor(True)
tensor(False)


# Tensor indexing

In [29]:
batch_size = 10
features = 25

x = torch.rand((batch_size, features))

print (x[0].shape)  # get the features from first batch
print (x[:, 0])     # get the first feature from all batches   

torch.Size([25])
tensor([0.9283, 0.1199, 0.1459, 0.5881, 0.4126, 0.9186, 0.2010, 0.2957, 0.9763,
        0.3981])


In [30]:
print (x[2, 0:10])  # get the 3rd example from the batch,and get first 10 features from that batch

tensor([0.1459, 0.7693, 0.5532, 0.7497, 0.7155, 0.5012, 0.7609, 0.7069, 0.1529,
        0.7247])


In [34]:
# useful operations
x = torch.arange(10)

z = torch.where(x>5, x, x*2)
print (z)

print (torch.tensor([0,0,1,1,2,3,4,4]).unique())
print (x.ndimension())

tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])
tensor([0, 1, 2, 3, 4])
1


# Tensor Reshaping

In [36]:
x = torch.arange(9)

x_3x3 = x.view(3,3)
print (x_3x3)
print (x_3x3.shape)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
torch.Size([3, 3])


In [37]:
x_3x3 = x.reshape(3,3)
print (x_3x3)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


In [38]:
y = x_3x3.t()
print (y)

tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])


In [42]:
print (y.contiguous().view(9))
print (y.reshape(9))

tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])
tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])


In [44]:
x1 = torch.rand((2,5))
x2 = torch.rand((2,5))

print (torch.cat((x1,x2), dim=0).shape)
print (torch.cat((x1,x2), dim=1).shape)

torch.Size([4, 5])
torch.Size([2, 10])


In [45]:
z = x1.view(-1)
print (z.shape)

torch.Size([10])


In [50]:
batch = 64
x = torch.rand((batch,2,5))

# we want to keep batch as it is but we want to flatten (2x5)
x = x.view(batch,-1)
print (x.shape) # 64 x 10

torch.Size([64, 10])


In [52]:
# switching axis
x = torch.rand((batch,2,5))
z = x.permute(0, 2, 1)
z.shape

torch.Size([64, 5, 2])

In [59]:
x = torch.arange(10)
print (x.shape)
print (x)
x = x.view(1,-1)
x.shape

torch.Size([10])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


torch.Size([1, 10])

In [57]:
print (x)

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])


In [60]:
x = torch.arange(10)
print (x.unsqueeze(0).shape)
print (x.unsqueeze(1).shape)

torch.Size([1, 10])
torch.Size([10, 1])


In [66]:
x = torch.arange(10).unsqueeze(0).unsqueeze(1)
x.shape

torch.Size([1, 1, 10])

In [67]:
print (x)

tensor([[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]])


In [71]:
z = x.squeeze(0)
z.shape

torch.Size([1, 10])