<a href="https://colab.research.google.com/github/palash04/Artificial-Intelligence/blob/master/Grokking_Deep_Learning/_01_Forward_Propagation_Intro_to_Neural_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# A simple neural network prediction

In [1]:
weight = 0.1
def neural_network(input,weight):
  prediction = input * weight
  return prediction

number_of_toes = [8.5,9.5,10,9]
input = number_of_toes[0]
pred = neural_network(input,weight)
print (pred)

0.8500000000000001


# Making a prediction with multiple inputs

In [2]:
# weighted sum
def w_sum(a,b):
  assert (len(a) == len(b))
  output = 0
  for i in range(len(a)):
    output += a[i] * b[i]
  return output

def neural_network(input,weights):
  pred = w_sum(input,weights)
  return pred

weights = [0.1,0.2,0]

# This dataset is the current
# status at the beginning of
# each game for the first 4 games
# in a season.

# toes = current number of toes
# wlrec = current games won (percent)
# nfans = fan count (in millions)

toes = [8.5,9.5,9.9,9.0]
wlrec = [0.65,0.8,0.8,0.9]
nfans = [1.2,1.3,0.5,1.0]

input = [toes[0],wlrec[0],nfans[0]]
pred = neural_network(input,weights)
print (pred)


0.9800000000000001


# Numpy code

In [3]:
import numpy as np
weights = np.array([0.1,0.2,0.0])
def neural_network(input,weights):
  pred = np.dot(input,weights)
  return pred

toes = np.array([8.5,9.5,9.9,9.0])
wlrec = np.array([0.65,0.8,0.8,0.9])
nfans = np.array([1.2,1.3,0.5,1.0])

input = np.array([toes[0],wlrec[0],nfans[0]])
pred = neural_network(input,weights)

print (pred)


0.9800000000000001


# Making a prediction with multiple outputs

In [5]:
# Instead of predicting just 
# whether the team won or lost, 
# now we're also predicting whether
# they are happy/sad AND the percentage
# of the team that is hurt. We are
# making this prediction using only
# the current win/loss record.

def elementwise_mul(number,vector):
  output = [0,0,0]
  assert (len(output) == len(vector))
  for i in range(len(vector)):
    output[i] = number * vector[i]
  return output

weights = [0.3,0.2,0.9]

def neural_network(input,weights):
  pred = elementwise_mul(input,weights)
  return pred

wlrec = [0.65,0.8,0.8,0.9]
input = wlrec[0]
pred = neural_network(input,weights)

print (pred)


[0.195, 0.13, 0.5850000000000001]


# Predicting with multiple inputs and multiple outputs


In [6]:
#inputs    #toes #win #fans
weights = [[0.1, 0.1, -0.3],    # hurt?
           [0.1, 0.2, 0.0],     # win?
           [0.0, 1.3, 0.1]]     # sad?

def w_sum(a,b):
  assert (len(a) == len(b))
  output = 0
  for i in range(len(a)):
    output += a[i] * b[i]
  return output

def vec_mat_mul(vect,matrix):
  assert (len(vect) == len(matrix))
  output = [0,0,0]
  for i in range(len(vect)):
    output[i] = w_sum(vect,matrix[i])
  return output

def neural_network(input,weights):
  pred = vec_mat_mul(input,weights)
  return pred

# This dataset is the current
# status at the beginning of
# each game for the first 4 games
# in a season.

# toes = current number of toes
# wlrec = current games won (percent)
# nfans = fan count (in millions)

toes =  [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65,0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

# Input corresponds to every entry
# for the first game of the season.

input = [toes[0],wlrec[0],nfans[0]]
pred = neural_network(input,weights)

print (pred)

[0.555, 0.9800000000000001, 0.9650000000000001]


# Predicting on Predictions
### Adding a hidden layer

In [9]:
#         #toes #win #fans
ih_wgt = [[0.1, 0.2, -0.1],     # hid[0]?
           [-0.1, 0.1, 0.9],    # hid[1]?
           [0.1, 0.4, 0.1]]     # hid[2]?

#         #hid[0] #hid[1] #hid[2]
hp_wgt = [[0.3, 1.1, -0.3],     # hurt?
           [0.2, 0.2, 0.0],     # win?
           [0.0, 1.3, 0.1]]     # sad?


weights = [ih_wgt, hp_wgt]

def neural_network(input,weights):
  hid = vec_mat_mul(input, weights[0])
  pred = vec_mat_mul(hid,weights[1])
  return pred

toes =  [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65,0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

input = [toes[0],wlrec[0],nfans[0]]
pred = neural_network(input,weights)

print (pred)

[0.21350000000000002, 0.23100000000000004, 0.5065]


# Numpy version

In [11]:
import numpy as np

#toes %win #fans
ih_wgt = np.array([ 
            [0.1, 0.2, -0.1], #hid[0]
            [-0.1,0.1, 0.9], #hid[1]
            [0.1, 0.4, 0.1]]).T #hid[2]


# hid[0] hid[1] hid[2]
hp_wgt = np.array([  
            [0.3, 1.1, -0.3], #hurt?
            [0.1, 0.2, 0.0], #win?
            [0.0, 1.3, 0.1] ]).T #sad?

weights = [ih_wgt, hp_wgt]

def neural_network(input,weights):
  hid = np.dot(input,weights[0])
  pred = np.dot(hid,weights[1])
  return pred

toes =  np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65,0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])

input = np.array([toes[0],wlrec[0],nfans[0]])
pred = neural_network(input,weights)

print (pred)


[0.2135 0.145  0.5065]


# Brushing up Numpy

In [14]:
import numpy as np
a = np.array([0,1,2,3]) # a vector
b = np.array([4,5,6,7]) # a vector
c = np.array([[0,1,2,3],
              [4,5,6,7]]) # a matrix

d = np.zeros((2,4))   # (2x4) matrix of zeros
e = np.random.rand(2,5)   # random (2x5) matrix 

print (a)
print (b)
print (c)
print (d)
print (e)




[0 1 2 3]
[4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0.43506592 0.8209236  0.18582937 0.40994848 0.83127374]
 [0.43845339 0.47079375 0.25043299 0.74533351 0.91331647]]


In [15]:
print (a * 0.01)  # multiplies every number in vector "a" by 0.01
print (c * 0.2)   # multiplies every number in matrix "c" by 0.2
print (a * b)     # multiplies elementwise between a and b (columns paired up)
print (a * b * 0.2) # elemeentwise multiplication and then multiplied by 0.2
print (a * c)     # elementwise multiplication on every row of matrix c

[0.   0.01 0.02 0.03]
[[0.  0.2 0.4 0.6]
 [0.8 1.  1.2 1.4]]
[ 0  5 12 21]
[0.  1.  2.4 4.2]
[[ 0  1  4  9]
 [ 0  5 12 21]]


In [16]:
a = np.zeros((2,4))
b = np.zeros((4,3))
c = np.dot(a,b)
print (c.shape)

(2, 3)


In [18]:
a = np.zeros((5,4)).T   # matrix with 5 rows and 4 columns, transposed matrix(4x5)
b = np.zeros((5,3))     # matrix with 5 rows and 3 columns
c = np.dot(a,b)
print (c.shape)

(4, 3)
